on:
    issues:
        types: [assigned]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          uses: jilgue/create-issue-branch@develop
          id: create_branch
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Checkout
          uses: actions/checkout@v2

        - name: Create dev ide in GCP
          uses: ./ # Uses an action in the root directory
          id: dev-ide
          with:
            SA_KEY: ${{ secrets.SA_KEY }}
            PROJECT: ${{ secrets.PROJECT }}
            REGION: ${{ secrets.REGION }}
            BUCKET: ${{ secrets.BUCKET }}
            BRANCH_NAME: ${{ steps.create_branch.outputs.branch-name }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # GITHUB_ACTOR set as environment variable
            # GITHUB_REPOSITORY set as environment variable
