on: [push]

jobs:
  gcp_ide_job:
    runs-on: ubuntu-latest
    name: Test gcp dev ide
    steps:
      - name: Get email
        run: |
          curl --request GET \
          --url https://api.github.com/user/emails \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
